# Generated by Django 3.0.3 on 2020-03-01 20:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('char_name', models.CharField(max_length=25)),
                ('base_health', models.IntegerField(verbose_name=5)),
            ],
        ),
    ]
